In [1]:
import pandas as pd
from rapidfuzz.distance import Levenshtein
from tqdm import tqdm

In [2]:
df = pd.read_csv("./Generate_positions/generated_puzzles.csv")
df_lichess = pd.read_csv("./Generate_positions/generated_puzzles_lichess_dataset_theme_distribution.csv")
df_lichess_large = pd.read_csv("./Generate_positions/generated_puzzles_lichess_dataset_theme_distribution_large.csv")
df_lichess_correct_ratings = pd.read_csv("./Generate_positions/generated_puzzles_lichess_dataset_theme_distribution_correct_ratings.csv")
df_ci_change_lichess = pd.read_csv("./Generate_positions/generated_puzzles_lichess_dataset_theme_distribution_counter_intuitive_metric_change.csv")
df_ci_relative_lichess_large = pd.read_csv("./Generate_positions/generated_puzzles_lichess_dataset_theme_distribution_counter_intuitive_metric_relative_large.csv")
df_good_rl_new_ci = pd.read_csv("./Generate_positions/GoodRLRunGenerations.csv")
df_good_rl_old_ci = pd.read_csv("./Generate_positions/GoodRLRunGenerationsOld.csv")
df_good_rl_new_ci_own_dist = pd.read_csv("./Generate_positions/GoodRLRunGenerations2.csv")
temp = pd.read_csv("./Generate_positions/v1.csv")

In [13]:
print(df["is_legal"].mean(), df[df["is_legal"]]["is_puzzle"].mean(), df[df["is_legal"] & df["is_puzzle"]]["counter_intuitive"].mean(), (df[df["is_legal"]]["is_puzzle"] & df[df["is_legal"]]["counter_intuitive"]).mean())
print(df_lichess["is_legal"].mean(), df_lichess[df_lichess["is_legal"]]["is_puzzle"].mean(), df_lichess[df_lichess["is_legal"] & df_lichess["is_puzzle"]]["counter_intuitive"].mean(), (df_lichess[df_lichess["is_legal"]]["is_puzzle"] & df_lichess[df_lichess["is_legal"]]["counter_intuitive"]).mean())
print(df_lichess_large["is_legal"].mean(), df_lichess_large[df_lichess_large["is_legal"]]["is_puzzle"].mean(), df_lichess_large[df_lichess_large["is_legal"] & df_lichess_large["is_puzzle"]]["counter_intuitive"].mean(), (df_lichess_large[df_lichess_large["is_legal"]]["is_puzzle"] & df_lichess_large[df_lichess_large["is_legal"]]["counter_intuitive"]).mean())
print(df_lichess_correct_ratings["is_legal"].mean(), df_lichess_correct_ratings[df_lichess_correct_ratings["is_legal"]]["is_puzzle"].mean(), df_lichess_correct_ratings[df_lichess_correct_ratings["is_legal"] & df_lichess_correct_ratings["is_puzzle"]]["counter_intuitive"].mean(), (df_lichess_correct_ratings[df_lichess_correct_ratings["is_legal"]]["is_puzzle"] & df_lichess_correct_ratings[df_lichess_correct_ratings["is_legal"]]["counter_intuitive"]).mean())
print(df_ci_change_lichess["is_legal"].mean(), df_ci_change_lichess[df_ci_change_lichess["is_legal"]]["is_puzzle"].mean(), df_ci_change_lichess[df_ci_change_lichess["is_legal"] & df_ci_change_lichess["is_puzzle"]]["counter_intuitive"].mean(), (df_ci_change_lichess[df_ci_change_lichess["is_legal"]]["is_puzzle"] & df_ci_change_lichess[df_ci_change_lichess["is_legal"]]["counter_intuitive"]).mean())
print(df_good_rl_new_ci["is_legal"].mean(), df_good_rl_new_ci[df_good_rl_new_ci["is_legal"]]["is_puzzle"].mean(), df_good_rl_new_ci[df_good_rl_new_ci["is_legal"] & df_good_rl_new_ci["is_puzzle"]]["counter_intuitive"].mean(), (df_good_rl_new_ci[df_good_rl_new_ci["is_legal"]]["is_puzzle"] & df_good_rl_new_ci[df_good_rl_new_ci["is_legal"]]["counter_intuitive"]).mean())
print(df_good_rl_old_ci["is_legal"].mean(), df_good_rl_old_ci[df_good_rl_old_ci["is_legal"]]["is_puzzle"].mean(), df_good_rl_old_ci[df_good_rl_old_ci["is_legal"] & df_good_rl_old_ci["is_puzzle"]]["counter_intuitive"].mean(), (df_good_rl_old_ci[df_good_rl_old_ci["is_legal"]]["is_puzzle"] & df_good_rl_old_ci[df_good_rl_old_ci["is_legal"]]["counter_intuitive"]).mean())
print(df_good_rl_new_ci_own_dist["is_legal"].mean(), df_good_rl_new_ci_own_dist[df_good_rl_new_ci_own_dist["is_legal"]]["is_puzzle"].mean(), df_good_rl_new_ci_own_dist[df_good_rl_new_ci_own_dist["is_legal"] & df_good_rl_new_ci_own_dist["is_puzzle"]]["counter_intuitive"].mean(), (df_good_rl_new_ci_own_dist[df_good_rl_new_ci_own_dist["is_legal"]]["is_puzzle"] & df_good_rl_new_ci_own_dist[df_good_rl_new_ci_own_dist["is_legal"]]["counter_intuitive"]).mean())

0.965 0.061139896373056994 0.01694915254237288 0.0010362694300518134
0.955 0.2094240837696335 0.01 0.0020942408376963353
0.9656 0.21644573322286662 0.0028708133971291866 0.0006213753106876554
0.973457532051282 0.1761498096511987 0.027453271028037383 0.004835888465891553
0.9749348958333334 0.17061769616026712 0.001304631441617743 0.00022259321090706732
0.985107421875 0.19306071871127634 0.005134788189987163 0.0009913258983890955
0.982177734375 0.19487944320159084 0.0012755102040816326 0.00024857071836937607
0.9754774305555556 0.08364849833147942 0.1023936170212766 0.008565072302558398

In [4]:
# this I think is correct
print(
    df["is_legal"].mean(), 
    df["is_puzzle"].mean(), 
    df[df["is_puzzle"]]["counter_intuitive"].mean(), 
    (df["is_puzzle"] & df["counter_intuitive"]).mean()
)

print(
    df_lichess["is_legal"].mean(), 
    df_lichess["is_puzzle"].mean(), 
    df_lichess[df_lichess["is_puzzle"]]["counter_intuitive"].mean(), 
    (df_lichess["is_puzzle"] & df_lichess["counter_intuitive"]).mean()
)

print(
    df_lichess_large["is_legal"].mean(), 
    df_lichess_large["is_puzzle"].mean(), 
    df_lichess_large[df_lichess_large["is_puzzle"]]["counter_intuitive"].mean(), 
    (df_lichess_large["is_puzzle"] & df_lichess_large["counter_intuitive"]).mean()
)

print(
    df_lichess_correct_ratings["is_legal"].mean(), 
    df_lichess_correct_ratings["is_puzzle"].mean(), 
    df_lichess_correct_ratings[df_lichess_correct_ratings["is_puzzle"]]["counter_intuitive"].mean(), 
    (df_lichess_correct_ratings["is_puzzle"] & df_lichess_correct_ratings["counter_intuitive"]).mean()
)

print(
    df_ci_change_lichess["is_legal"].mean(), 
    df_ci_change_lichess["is_puzzle"].mean(), 
    df_ci_change_lichess[df_ci_change_lichess["is_puzzle"]]["counter_intuitive"].mean(), 
    (df_ci_change_lichess["is_puzzle"] & df_ci_change_lichess["counter_intuitive"]).mean()
)

print(
    df_ci_relative_lichess_large["is_legal"].mean(), 
    df_ci_relative_lichess_large["is_puzzle"].mean(), 
    df_ci_relative_lichess_large[df_ci_relative_lichess_large["is_puzzle"]]["counter_intuitive"].mean(), 
    (df_ci_relative_lichess_large["is_puzzle"] & df_ci_relative_lichess_large["counter_intuitive"]).mean()
)

print(
    df_good_rl_new_ci["is_legal"].mean(), 
    df_good_rl_new_ci["is_puzzle"].mean(), 
    df_good_rl_new_ci[df_good_rl_new_ci["is_puzzle"]]["counter_intuitive"].mean(), 
    (df_good_rl_new_ci["is_puzzle"] & df_good_rl_new_ci["counter_intuitive"]).mean()
)

print(
    df_good_rl_old_ci["is_legal"].mean(), 
    df_good_rl_old_ci["is_puzzle"].mean(), 
    df_good_rl_old_ci[df_good_rl_old_ci["is_puzzle"]]["counter_intuitive"].mean(), 
    (df_good_rl_old_ci["is_puzzle"] & df_good_rl_old_ci["counter_intuitive"]).mean()
)

print(
    df_good_rl_new_ci_own_dist["is_legal"].mean(), 
    df_good_rl_new_ci_own_dist["is_puzzle"].mean(), 
    df_good_rl_new_ci_own_dist[df_good_rl_new_ci_own_dist["is_puzzle"]]["counter_intuitive"].mean(), 
    (df_good_rl_new_ci_own_dist["is_puzzle"] & df_good_rl_new_ci_own_dist["counter_intuitive"]).mean()
)

print(
    temp["is_legal"].mean(), 
    temp["is_puzzle"].mean(), 
    temp[temp["is_puzzle"]]["counter_intuitive"].mean(), 
    (temp["is_puzzle"] & temp["counter_intuitive"]).mean()
)

0.965 0.059 0.01694915254237288 0.001
0.955 0.2 0.01 0.002
0.9656 0.209 0.0028708133971291866 0.0006
0.973457532051282 0.17147435897435898 0.027453271028037383 0.004707532051282051
0.9749348958333334 0.16634114583333334 0.001304631441617743 0.00021701388888888888
0.973876953125 0.17046101888020834 0.007280539476039864 0.0012410481770833333
0.985107421875 0.190185546875 0.005134788189987163 0.0009765625
0.982177734375 0.19140625 0.0012755102040816326 0.000244140625
0.9754774305555556 0.08159722222222222 0.1023936170212766 0.008355034722222222
0.9682074652777778 0.119140625 0.007285974499089253 0.0008680555555555555

In [ ]:
dataset = pd.read_csv("./dataset/dataset.csv", chunksize=100_000)
external_puzzles = set()
for chunk in dataset:
    clean_puzzles = chunk["Puzzle_FEN"].str.split(" ").str[:4].str.join(" ")

    external_puzzles.update(clean_puzzles)
print(f"Total unique FENs in external dataset: {len(external_puzzles)}")
processed_lichess_fens = df_lichess_correct_ratings["fen"].fillna("").str.split(" ").str[:4].str.join(" ")
df_lichess_correct_ratings["is_overlap"] = processed_lichess_fens.isin(external_puzzles)
print(df_lichess_correct_ratings["is_overlap"].value_counts())

Total unique FENs in external dataset: 5565407
is_overlap
False    9211
True        5
Name: count, dtype: int64

In [36]:
import re

def fen_to_padded(fen):
    board, side, castling, enpassant = fen.split(" ")[:4]
    board = re.sub(r"\d", lambda digit: "." * int(digit.group()), board)
    board = re.sub("/", "", board)
    castling = "".join([char if char in castling else "." for char in "KQkq"])
    enpassant = ".." if enpassant != "-" else enpassant
    return " ".join([board, side, castling, enpassant])

for i, row in enumerate(chunk.iterrows()):
    print(row[1]["Puzzle_FEN"], fen_to_padded(row[1]["Puzzle_FEN"]))
    if i > 5:
        break

8/p2kb2Q/1p5p/P5p1/2pN4/n1PpqP1P/1P4P1/1N1K3R b - - 6 37 ........p..kb..Q.p.....pP.....p...pN....n.PpqP.P.P....P..N.K...R b .... -
8/2P3pk/p4p1p/3p1b2/5qPP/P6Q/6BK/8 w - - 1 37 ..........P...pkp....p.p...p.b.......qPPP......Q......BK........ w .... -
r4r1k/pp1n1pp1/2p4p/2p1p2n/2B1P3/3P1q1P/PPPQNPRK/6R1 w - - 2 17 r....r.kpp.n.pp...p....p..p.p..n..B.P......P.q.PPPPQNPRK......R. w .... -
rn1q1rk1/4b2n/3p3Q/p2Pp3/P1B3b1/2N2N2/1P3PP1/R4RK1 w - - 1 21 rn.q.rk.....b..n...p...Qp..Pp...P.B...b...N..N...P...PP.R....RK. w .... -
8/kp3R2/pNr2p2/P4bp1/K1P5/1P4P1/8/5n2 w - - 3 42 ........kp...R..pNr..p..P....bp.K.P......P....P..............n.. w .... -
4r1k1/p4ppp/6N1/3p4/q1pP1Q2/1n6/5PPP/4R1K1 w - - 1 29 ....r.k.p....ppp......N....p....q.pP.Q...n...........PPP....R.K. w .... -
3b4/1p3ppp/3N4/3k4/1n3B2/1P6/P4PPP/6K1 b - - 4 23 ...b.....p...ppp...N.......k.....n...B...P......P....PPP......K. b .... -

In [ ]:
external_list = []
for fen in tqdm(external_puzzles):
    external_list.append(fen_to_padded(fen))

In [ ]:
# external_list = list(external_puzzles)
# external_list = []
# for fen in tqdm(external_puzzles):
#     external_list.append(fen_to_padded(fen))
unique_lichess_fens = processed_lichess_fens.unique()[:100]
unique_lichess_fens = [fen_to_padded(fen) for fen in unique_lichess_fens]

min_distances = {}

print(f"Computing distances for {len(unique_lichess_fens)} unique Lichess positions...")

for i, l_fen in tqdm(enumerate(unique_lichess_fens)):
    if not l_fen:
        continue
    
    minimum = min(Levenshtein.distance(l_fen, e_fen) for e_fen in external_list)
    min_distances[l_fen] = minimum

print(f"Average min Edit Distance: {sum(min_distances.values()) / len(min_distances)}")

Computing distances for 10 unique Lichess positions...

10it [01:18,  7.81s/it]

Average min Edit Distance: 9.1

In [38]:
import random


# external_list = list(external_puzzles)
# external_list = []
# for fen in tqdm(external_puzzles):
#     external_list.append(fen_to_padded(fen))
sample_size = 100
random_sample_fens = random.sample(external_list, sample_size)

min_distances = {}

print(f"Computing minimum nonzero distances for {sample_size} random positions from external_list...")

for s_fen in tqdm(random_sample_fens):
    if not s_fen:
        continue
    
    distances = (Levenshtein.distance(s_fen, e_fen) for e_fen in external_list)
    nonzero_distances = (d for d in distances if d > 0)
    
    minimum = min(nonzero_distances)
    min_distances[s_fen] = minimum

avg_dist = sum(min_distances.values()) / len(min_distances)
print(f"Average min nonzero Edit Distance: {avg_dist}")

Computing minimum nonzero distances for 10 random positions from external_list...

100%|██████████| 10/10 [01:18<00:00,  7.86s/it]

Average min nonzero Edit Distance: 10.4

In [25]:
df[df["is_legal"] & df["is_puzzle"] & df["counter_intuitive"]]

,target_themes,target_rating,fen,is_legal,is_puzzle,counter_intuitive,actual_themes,predicted_rating,themes_match
47,"['veryLong', 'endgame', 'queenEndgame', 'crush...",2884.556641,6k1/pp1Q1pp1/2p1p2p/2P1P1PP/1P3P2/3K4/8/7q w -...,True,True,True,"['endgame', 'mateIn3', 'mate', 'queenEndgame',...",0.398133,False

In [18]:
df_lichess[df_lichess["is_legal"] & df_lichess["is_puzzle"] & df_lichess["counter_intuitive"]]

,target_themes,target_rating,fen,is_legal,is_puzzle,counter_intuitive,actual_themes,predicted_rating,themes_match
238,"['bishopEndgame', 'crushing', 'defensiveMove',...",125.0,8/7K/6p1/8/6k1/3p4/3B4/8 b - - 0 53,True,True,True,"['endgame', 'advantage', 'advancedPawn', 'quie...",1788.979980,False
350,"['mate', 'mateIn2', 'middlegame', 'short']",24.0,3r2k1/pp1q3p/6p1/2Q1RnN1/5R2/P5Pb/1P2P2P/6K1 b...,True,True,True,"['middlegame', 'mateIn2', 'mate', 'short']",1050.020508,True

In [ ]:
with pd.option_context("display.max_colwidth", 500):
    display(df_lichess_large[df_lichess_large["is_legal"] & df_lichess_large["is_puzzle"] & df_lichess_large["counter_intuitive"]][["fen", "target_themes", "actual_themes", "predicted_rating"]])

,fen,target_themes,actual_themes,predicted_rating
1022,N4k2/3n2r1/pp1P1p1n/5Pqp/2P2pp1/1P6/P3RPPP/4R1K1 w - - 0 30,"['fork', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'short']",626.755493
3869,4k3/Rp1n1qpr/2p1r3/B7/2p5/2P4P/2P1QbP1/4R2K w - - 0 29,"['advantage', 'fork', 'long', 'middlegame']","['middlegame', 'advantage', 'exposedKing', 'long']",1872.460571
5814,7k/1b2r1p1/5r2/p1pp4/3q1b2/P1N5/1P2QPPP/1B2R1K1 w - - 0 28,"['long', 'mate', 'mateIn3', 'middlegame', 'sacrifice']","['middlegame', 'advantage', 'discoveredAttack', 'kingsideAttack', 'short']",1411.959717
7458,6k1/p2nr1Pr/1p5p/1b1p4/3P3q/4PR2/PP3RPP/5QK1 w - - 1 29,"['advancedPawn', 'mate', 'mateIn2', 'middlegame', 'promotion', 'short']","['middlegame', 'mateIn3', 'mate', 'exposedKing', 'kingsideAttack', 'long']",1248.470703
7710,r3r1k1/pp1b1ppp/8/q2pR3/5N2/1P6/1P2QPPP/4R1K1 w - - 0 20,"['advantage', 'fork', 'middlegame', 'veryLong']","['middlegame', 'mateIn3', 'mate', 'backRankMate', 'long']",775.752197
9797,6kq/p1pr1p1p/1bp3pP/8/4N3/6Pb/PPP2P2/4R1KR w - - 0 24,"['discoveredAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'kingsideAttack', 'short']",1005.286377

In [8]:
with pd.option_context("display.max_colwidth", 500):
    display(df_lichess_correct_ratings[df_lichess_correct_ratings["is_legal"] & df_lichess_correct_ratings["is_puzzle"] & df_lichess_correct_ratings["counter_intuitive"]][["fen", "target_themes", "actual_themes", "predicted_rating"]])

,fen,target_themes,actual_themes,predicted_rating
219,r1bq1r1k/p5bp/1pn1Q1p1/n1p3N1/P1B2P2/2PP4/6PP/R1B2RK1 w - - 5 18,"['kingsideAttack', 'master', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short', 'smotheredMate']","['middlegame', 'mateIn2', 'mate', 'smotheredMate', 'sacrifice', 'kingsideAttack', 'short']",1534.806641
229,8/5p1p/2k2Bp1/8/3p1PP1/6KP/1bP5/8 b - - 1 36,"['bishopEndgame', 'crushing', 'endgame', 'short', 'skewer']","['endgame', 'advantage', 'discoveredAttack', 'bishopEndgame', 'short']",1107.149170
384,5rk1/5qpp/4p3/3pQ3/3P4/6R1/PPr2PPP/5RK1 b - - 1 25,"['endgame', 'master', 'mate', 'mateIn4', 'sacrifice', 'veryLong']","['endgame', 'mateIn4', 'mate', 'sacrifice', 'veryLong']",1475.327026
401,r1bq1rk1/1pp2pp1/2nb1n2/p2Np1Np/3P3P/4P3/PPQ2PP1/R1B1KB1R w KQ - 0 11,"['kingsideAttack', 'mate', 'mateIn2', 'opening', 'short']","['middlegame', 'mateIn2', 'mate', 'kingsideAttack', 'short']",1221.063110
419,r4r1k/pp2Nppp/4n3/3p3R/8/2P1R3/PP6/2K5 w - - 1 25,"['anastasiaMate', 'attraction', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn2', 'mate', 'anastasiaMate', 'attraction', 'sacrifice', 'short']",1389.271729
657,r1bqrbk1/1p1p1R1p/p1p3p1/4PN1n/2Bn1P2/2N5/PPP2P1P/R3K2R w KQ - 0 18,"['doubleCheck', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'doubleCheck', 'kingsideAttack', 'short']",1997.696777
740,r2q1r1k/1b3p2/1p2pNnb/3pP3/8/pPp1P1P1/P1P1BPK1/3R3R w - - 0 24,"['hookMate', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'hookMate', 'hangingPiece', 'kingsideAttack', 'short']",1096.088745
749,2R2r1k/pp5p/4Q1n1/4p3/4P2P/6PB/P4P1K/3q1r2 w - - 11 31,"['attraction', 'long', 'mate', 'mateIn3', 'middlegame', 'sacrifice']","['middlegame', 'mateIn2', 'mate', 'pin', 'short']",1541.887451
1035,6k1/5p2/p4B1p/1pbpQ3/8/2PB3P/5qbK/8 w - - 0 30,"['advantage', 'deflection', 'endgame', 'master', 'veryLong']","['endgame', 'mateIn4', 'mate', 'attraction', 'deflection', 'sacrifice', 'fork', 'veryLong']",2009.621704
1154,2r2r2/1p3pkp/p4np1/2P1Q3/5N2/3BP2P/3q1PP1/5RK1 w - - 0 26,"['advantage', 'middlegame', 'short']","['middlegame', 'advantage', 'deflection', 'sacrifice', 'long']",1913.974365
1158,1Q1R4/5pkp/1p1p4/2rPp3/1P6/8/PPq1r2P/KR6 b - - 0 33,"['attraction', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'short']",1402.728027
1176,2k5/2p2ppp/pq6/1p4Q1/8/Pr3P1P/5P2/4R1K1 w - - 0 25,"['advantage', 'defensiveMove', 'endgame', 'veryLong']","['endgame', 'advantage', 'deflection', 'fork', 'veryLong']",1835.946655
1497,8/R5pp/1p4k1/2p3rn/P3P3/4bP2/1PP3PP/3R3K b - - 0 24,"['clearance', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'short']",1074.838135
1783,2b3k1/2p3pp/3p2r1/3Pp2q/2P1Pp2/5P2/5QPP/4N1RK b - - 3 33,"['attraction', 'endgame', 'kingsideAttack', 'master', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn3', 'mate', 'attraction', 'sacrifice', 'kingsideAttack', 'long']",1266.761475
2284,2k1r2r/ppq2p2/3bb1p1/2pN4/6P1/1P6/P1PPQPB1/R3R1K1 b - - 0 19,"['advantage', 'kingsideAttack', 'long', 'middlegame', 'sacrifice']","['middlegame', 'advantage', 'veryLong']",1984.945557
2534,5rk1/ppb1q3/2p3pQ/5p1R/4p3/2P5/PP3PPP/6K1 w - - 0 33,"['endgame', 'mate', 'mateIn2', 'short']","['endgame', 'advantage', 'exposedKing', 'skewer', 'long']",1650.163452
2888,6r1/5p1p/2Qpk3/4p3/5qr1/8/PPP1RP1P/R6K b - - 5 26,"['endgame', 'master', 'mate', 'mateIn1', 'oneMove']","['endgame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'short']",1726.293701
2952,4r2k/pp1R4/5R1p/5pnQ/1q6/7P/P5P1/7K b - - 7 35,"['advantage', 'endgame', 'long']","['endgame', 'mateIn3', 'mate', 'long']",1241.219482
3142,r1Bq1rk1/2p3pp/p7/1pb1pp2/3nP3/3P3P/PPP3PN/R1BQ1RK1 b - - 0 14,"['doubleCheck', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'doubleCheck', 'kingsideAttack', 'short']",1683.158203
3590,1nr3k1/6p1/p3p2r/3pNp1n/1P1P3q/P1P5/3BBPP1/R2Q1RK1 b - - 4 29,"['attraction', 'doubleCheck', 'kingsideAttack', 'long', 'mate', 'mateIn3', 'middlegame', 'sacrifice']","['middlegame', 'mateIn3', 'mate', 'attraction', 'doubleCheck', 'sacrifice', 'kingsideAttack', 'long']",1791.171997
3657,2r2rk1/pbq1bpp1/1p1ppn1p/2p3NN/1PP5/P2QP3/1B1P1PPP/R3K2R w KQ - 0 15,"['kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'kingsideAttack', 'short']",1300.223877
4182,4r1k1/2p2p2/p2q1Pp1/1p4QR/6P1/1PP4K/8/1b6 w - - 1 28,"['attraction', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'attraction', 'sacrifice', 'long']",1423.131348
4228,3r1rk1/p3p2p/6pQ/2q5/8/6R1/PP3PPP/5RK1 b - - 2 26,"['endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'sacrifice', 'long']",1328.694580
4691,8/1R6/6pk/p2p4/1p1P1PP1/6K1/8/1r6 w - - 2 52,"['endgame', 'mate', 'mateIn2', 'rookEndgame', 'short']","['endgame', 'mateIn2', 'mate', 'rookEndgame', 'short']",949.715332
4719,1R4nk/5ppp/pQ1p1r2/2p5/2P2P2/8/q5PP/6K1 w - - 0 29,"['attraction', 'backRankMate', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'backRankMate', 'attraction', 'sacrifice', 'short']",1097.133545
5012,r1bq2kr/p4pbp/3p2pB/1ppP4/2n1N3/5Q1P/PPP2PP1/R3R1K1 w - - 2 17,"['advantage', 'kingsideAttack', 'long', 'middlegame', 'sacrifice']","['middlegame', 'advantage', 'short']",2044.560181
5149,2kr4/1p3pRp/p1pq4/8/4Q3/8/PPP2P1P/2K1R3 b - - 0 23,"['backRankMate', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'backRankMate', 'sacrifice', 'long']",1126.882812
5311,b4rk1/2p2ppp/p1p5/1pP1q3/8/PQ6/BP4PP/3R2K1 w - - 0 21,"['endgame', 'fork', 'long', 'mate', 'mateIn3', 'pin', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'sacrifice', 'fork', 'pin', 'long']",1333.272339
5929,7q/8/r4pp1/3p3p/8/p3PkPQ/1r3P2/3R2K1 w - - 4 42,"['discoveredAttack', 'endgame', 'long', 'mate', 'mateIn3']","['endgame', 'crushing', 'discoveredAttack', 'short']",1665.850952
6189,4r1k1/1p4pp/8/p7/P3q2P/1Pb2Q2/6P1/5R1K w - - 0 27,"['backRankMate', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'backRankMate', 'sacrifice', 'long']",1152.665283
6465,r4nk1/6pp/p2p4/1p3Q1B/3qbR2/8/PP4PP/7K w - - 0 29,"['backRankMate', 'deflection', 'long', 'mate', 'mateIn3', 'middlegame']","['middlegame', 'mateIn3', 'mate', 'backRankMate', 'deflection', 'long']",1398.461182
6943,2k1r3/ppp1q2p/6p1/8/5R2/1QP2N2/PP3PPP/5K2 b - - 0 23,"['backRankMate', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'backRankMate', 'sacrifice', 'long']",1044.314209
7449,6k1/ppp2pp1/3b3p/3P4/2P1b2N/1Q4PP/PP2rR2/6K1 b - - 3 28,"['endgame', 'mate', 'mateIn2', 'short']","['endgame', 'crushing', 'short']",1670.359863
7454,8/6Q1/3Pb2p/3qPk2/7P/4B1K1/8/1q6 w - - 0 58,"['endgame', 'master']","['endgame', 'mateIn2', 'mate', 'short']",1644.651978
7482,5r1k/1p4p1/p2p1qQp/3B4/4R3/8/P1P3PP/4R1K1 b - - 3 30,"['backRankMate', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'backRankMate', 'sacrifice', 'long']",1156.782959
7626,5rkb/p4p2/1p1rpqNp/2p5/4Q3/2P5/PPB2PP1/4R1K1 w - - 1 26,"['clearance', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short']","['middlegame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'kingsideAttack', 'short']",1210.318848
7660,2r3k1/p4ppp/1pQ1b3/1N2P3/8/7q/PPP4P/2KR4 w - - 4 26,"['backRankMate', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'backRankMate', 'sacrifice', 'short']",1105.174316
7825,7k/2qrb1p1/5pP1/p1p1p3/PpP1Q3/1P2BK1P/3r1P2/8 w - - 0 33,"['long', 'mate', 'mateIn3', 'middlegame']","['endgame', 'mateIn3', 'mate', 'kingsideAttack', 'long']",1058.062256
8171,r1bq3r/pp3pk1/2p3p1/3pP3/3P1Pn1/P1NB2P1/1P1QR1P1/2R3K1 b - - 8 21,"['attraction', 'kingsideAttack', 'mate', 'mateIn4', 'middlegame', 'sacrifice', 'veryLong']","['middlegame', 'mateIn4', 'mate', 'attraction', 'sacrifice', 'kingsideAttack', 'veryLong']",1464.785522
8642,5rk1/1p3ppp/p4r2/3R4/8/Q5P1/PPq2P1P/4R1K1 w - - 1 24,"['attraction', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'short']",1189.107666
8678,6k1/p3R1pp/2Q1pr2/8/3r4/1P6/q4PPP/5RK1 b - - 1 26,"['endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'sacrifice', 'long']",1428.974609
8801,4k1r1/2q1bp2/pp3p2/3p1Q2/3P4/2P2NPp/PP6/4RRK1 b - - 0 24,"['kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'kingsideAttack', 'short']",1075.740234
9107,r2q1rk1/pb3pp1/1p2p2p/2p5/2PPNn1P/3Q4/PPB2PP1/2KRR3 w - - 3 20,"['clearance', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short']","['middlegame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'kingsideAttack', 'short']",1004.034851
9429,r4bk1/pbp3pp/2q5/2p2Q2/7r/2N4P/PPP3P1/R4RK1 w - - 0 23,"['backRankMate', 'deflection', 'long', 'mate', 'mateIn3', 'middlegame', 'sacrifice']","['middlegame', 'mateIn3', 'mate', 'backRankMate', 'deflection', 'long']",1099.663086
9498,2r1r1k1/5ppp/R7/1p3Q2/3P4/8/1P3PPP/2q2RK1 b - - 2 21,"['attraction', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'short']",1185.277588
9739,r4rk1/1b2bpp1/p3p2p/1p6/2n1Nq2/2PQ1N1P/PPB2PP1/R4RK1 w - - 3 19,"['clearance', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short']","['middlegame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'kingsideAttack', 'short']",1061.611694
9901,5rk1/5ppp/8/4P3/2Q5/1p4PK/rq2P2P/2R2R2 w - - 0 30,"['clearance', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'sacrifice', 'clearance', 'long']",1402.480225

In [6]:
with pd.option_context("display.max_colwidth", 500):
    display(df_ci_relative_lichess_large[df_ci_relative_lichess_large["is_legal"] & df_ci_relative_lichess_large["is_puzzle"] & df_ci_relative_lichess_large["counter_intuitive"]][["fen", "target_themes", "actual_themes", "predicted_rating"]])

,fen,target_themes,actual_themes,predicted_rating
699,2r4r/pp2Qp2/1qk4p/3p2p1/3b4/P5B1/1P3PPP/4R1K1 w - - 4 23,"['advantage', 'long', 'middlegame', 'pin']","['middlegame', 'advantage', 'quietMove', 'defensiveMove', 'short']",2297.805908
1592,7k/1p1n2pp/1RP2rr1/8/2Q1p3/4P1Bq/5P1P/R6K b - - 0 38,"['mate', 'mateIn2', 'middlegame', 'sacrifice', 'short']","['middlegame', 'crushing', 'defensiveMove', 'short']",2172.173828
1687,rn3rk1/p4ppp/2p1b3/6B1/1Qp1P3/5N2/qP3PPP/2KR3R w - - 0 15,"['attraction', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short']","['middlegame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'kingsideAttack', 'short']",1523.997803
2713,1k1r4/5pQp/2p5/p7/1pP5/1P6/P3NPPP/4qBK1 b - - 0 32,"['attraction', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'backRankMate', 'attraction', 'sacrifice', 'short']",1226.806274
4448,3r3k/7p/p1Q1Bqp1/1p6/8/2b5/P1r2PPP/2R2RK1 b - - 0 23,"['backRankMate', 'deflection', 'fork', 'mate', 'mateIn4', 'middlegame', 'sacrifice', 'veryLong']","['middlegame', 'advantage', 'defensiveMove', 'short']",2062.444824
...,...,...,...,...
95547,r2qr2k/1p2pQbp/6p1/p3N3/P2Pb3/1B2B3/1P3PPP/R5K1 w - - 1 19,"['kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short', 'smotheredMate']","['middlegame', 'mateIn2', 'mate', 'smotheredMate', 'sacrifice', 'kingsideAttack', 'short']",1351.854370
95581,r2qk1nr/pppnb1pp/4pp2/3pN3/3P1B2/4P3/PPP2PPP/R2QKB1R w KQkq - 0 9,"['advantage', 'long', 'opening']","['opening', 'advantage', 'trappedPiece', 'pin', 'long']",1249.098633
95691,6k1/2q3pp/p1P2p1r/1p2n3/1P6/P4QP1/5PP1/3R2K1 w - - 1 32,"['advancedPawn', 'advantage', 'endgame', 'veryLong']","['endgame', 'advantage', 'advancedPawn', 'veryLong']",1994.775757
96947,r5k1/7p/p2p1r2/1P2p1pq/4Pp2/1P3P2/P3QRPP/6RK b - - 0 25,"['attraction', 'endgame', 'kingsideAttack', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'kingsideAttack', 'short']",1306.875610
97291,2kr1b1r/pp1npp2/2p2n2/5qpp/2B2B2/2N2Q1P/PPP2PP1/R4RK1 w - - 0 14,"['bodenMate', 'mate', 'mateIn2', 'middlegame', 'queensideAttack', 'sacrifice', 'short']","['middlegame', 'mateIn2', 'mate', 'bodenMate', 'sacrifice', 'queensideAttack', 'short']",1187.194092

In [17]:
with pd.option_context("display.max_colwidth", 500):
    display(df_good_rl_new_ci_own_dist[df_good_rl_new_ci_own_dist["is_legal"] & df_good_rl_new_ci_own_dist["is_puzzle"] & df_good_rl_new_ci_own_dist["counter_intuitive"]][["fen", "target_themes", "actual_themes", "predicted_rating"]])

,fen,target_themes,actual_themes,predicted_rating
190,2kr3r/ppp1qppp/3p4/3QnP2/5B2/8/PPP2PPP/R3KB1R b KQ - 0 13,"['veryLong', 'middlegame', 'crushing', 'doubleCheck']","['middlegame', 'mateIn2', 'mate', 'doubleCheck', 'short']",1630.594849
272,r7/pppkq2p/3p4/4nP1Q/8/8/PPP2PPP/RN2KB1R b KQ - 0 14,"['short', 'middlegame', 'crushing', 'doubleCheck']","['middlegame', 'mateIn2', 'mate', 'doubleCheck', 'short']",1653.070190
814,8/1p3p2/p4P1p/3pP3/1P6/P3b2k/1B6/7K b - - 3 34,"['long', 'endgame', 'bishopEndgame', 'advantage', 'interference']","['endgame', 'advantage', 'quietMove', 'defensiveMove', 'bishopEndgame', 'long']",2128.194824
966,r1b2rk1/ppp1qppp/3b4/3P4/2B2n2/2N5/PPPB1PPP/R2Q1RK1 b - - 6 11,"['short', 'opening', 'advantage', 'kingsideAttack']","['opening', 'advantage', 'discoveredAttack', 'long']",1958.689575
1062,1k1r1bnr/ppp1q1pp/5p2/1Q1Pn3/3P1B2/2N5/PPP2PPP/R3KB1R b KQ - 2 11,"['veryLong', 'opening', 'advantage', 'doubleCheck']","['opening', 'mateIn2', 'mate', 'doubleCheck', 'short']",1445.126099
...,...,...,...,...
8757,r1bk2nr/ppppq1pp/8/3QnP2/3P1B2/7P/PPP2PP1/RN2KB1R b KQ - 2 8,"['oneMove', 'opening', 'advantage', 'doubleCheck']","['opening', 'mateIn2', 'mate', 'doubleCheck', 'short']",1408.291748
8809,r3kb1r/p1p2ppp/3p1n2/1N2p3/2b1q3/3P4/PP2BKPP/R1B1Q1NR b kq - 0 13,"['short', 'opening', 'advantage', 'fork']","['opening', 'advantage', 'short']",1678.623779
8991,8/p2k1p2/3p1Ppp/2pP4/2Pp2P1/1P1P1K1P/8/8 b - - 2 36,"['oneMove', 'endgame', 'pawnEndgame', 'advantage', 'attackingF2F7']","['endgame', 'advantage', 'defensiveMove', 'pawnEndgame', 'long']",2032.399170
9080,r1bk1b1r/ppp1q1pp/3p1p2/4nP1Q/3P4/8/PPP2PPP/RNB1KBNR b KQ - 0 9,"['short', 'opening', 'advantage', 'doubleCheck']","['opening', 'mateIn2', 'mate', 'doubleCheck', 'short']",1529.112427
9115,r3kb1r/pp2qppp/3p4/3QnP2/5B2/8/PPP2PPP/R3KB1R b KQkq - 0 12,"['long', 'middlegame', 'advantage', 'doubleCheck']","['middlegame', 'mateIn2', 'mate', 'doubleCheck', 'short']",1673.581909

In [7]:
dataset = pd.read_csv("./dataset/dataset.csv", nrows=100_000)
targets = {"mate", "sacrifice", "middlegame"}
mask = dataset["Themes"].str.split().apply(lambda x: targets.issubset(set(x)))
dataset[mask]

,Unnamed: 0,FEN,Moves,Rating,Themes,Puzzle_FEN
115,115,4rr1k/pQpn2pp/3p1q2/8/8/2P5/PP3PPP/RN3RK1 w - ...,b7c7 f6f2 f1f2 e8e1 f2f1 e1f1,1209,kingsideAttack long mate mateIn3 middlegame sa...,4rr1k/p1Qn2pp/3p1q2/8/8/2P5/PP3PPP/RN3RK1 b - ...
140,140,1r6/pp2kpp1/2n1p1n1/3p2PQ/5P2/2PqP3/PP1N4/2KR3...,h5h7 c6b4 c3b4 b8c8 d2c4 c8c4,1901,long mate mateIn3 middlegame queensideAttack s...,1r6/pp2kppQ/2n1p1n1/3p2P1/5P2/2PqP3/PP1N4/2KR3...
177,177,rn3rk1/4pp1p/3p2pB/2q4P/3bP1b1/Pp2Q3/1P2B3/1K1...,e3d4 c5c2 b1a1 a8a3 b2a3 c2a2,1764,long mate mateIn3 middlegame queensideAttack s...,rn3rk1/4pp1p/3p2pB/2q4P/3QP1b1/Pp6/1P2B3/1K1R2...
279,279,r6r/pp2kb2/3p1p1Q/1N1Pp3/3bP3/P2B2P1/1P4PP/7K ...,h6d2 h8h2 h1h2 a8h8 d2h6 h8h6,1382,attraction kingsideAttack long mate mateIn3 mi...,r6r/pp2kb2/3p1p2/1N1Pp3/3bP3/P2B2P1/1P1Q2PP/7K...
301,301,1r5r/5pk1/4p3/2Np2PP/p1nP4/n1P5/P3B3/K1R4R w -...,c5a4 b8b1 c1b1 a3c2,1495,mate mateIn2 middlegame sacrifice short,1r5r/5pk1/4p3/3p2PP/N1nP4/n1P5/P3B3/K1R4R b - ...
...,...,...,...,...,...,...
99831,99831,5rrk/p5p1/1pR3Qp/4Pn1P/6R1/8/P4qPK/8 b - - 4 38,f5e3 g6h6 g7h6 c6h6,1068,mate mateIn2 middlegame sacrifice short,5rrk/p5p1/1pR3Qp/4P2P/6R1/4n3/P4qPK/8 w - - 5 39
99844,99844,r4rk1/pppR1p2/2n1p1p1/7p/5q2/2Q2P2/PPP5/1K4R1 ...,a7a5 g1g6 f7g6 c3g7,1023,kingsideAttack mate mateIn2 middlegame sacrifi...,r4rk1/1ppR1p2/2n1p1p1/p6p/5q2/2Q2P2/PPP5/1K4R1...
99901,99901,5rk1/pr5p/2b1pPp1/3qQ3/3pnP1B/1Pp4R/P1P3PP/R4B...,f1c4 e4f2 h4f2 d5g2,1126,discoveredAttack kingsideAttack mate mateIn2 m...,5rk1/pr5p/2b1pPp1/3qQ3/2BpnP1B/1Pp4R/P1P3PP/R6...
99971,99971,r4r1k/pbp1N1pp/1p1p4/7Q/3qp3/3B2K1/PPP3R1/5R2 ...,f8f1 h5h7 h8h7 g2h2,1516,anastasiaMate attraction kingsideAttack mate m...,r6k/pbp1N1pp/1p1p4/7Q/3qp3/3B2K1/PPP3R1/5r2 w ...
99990,99990,r5k1/4prb1/p4pQR/3qpP1N/7p/8/P5P1/7K b - - 1 29,a8c8 g6h7 g8f8 h7h8 g7h8 h6h8,1942,exposedKing long mate mateIn3 middlegame sacri...,2r3k1/4prb1/p4pQR/3qpP1N/7p/8/P5P1/7K w - - 2 30

In [8]:
dataset = pd.read_csv("./dataset/dataset.csv", chunksize=100_000)
external_puzzles = set()
for chunk in dataset:
    clean_puzzles = chunk["Puzzle_FEN"].str.split(" ").str[:4].str.join(" ")
    external_puzzles.update(clean_puzzles)
external_puzzles_list = list(external_puzzles)

In [9]:
min_dist = float("inf")
closest_fen = None
for fen in external_puzzles_list:
    dist = Levenshtein.distance("6rk/p2R3p/2p4r/6p1/8/2N1KQq1/PP6/3R4 b - -", fen)
    if dist < min_dist:
        min_dist = dist
        closest_fen = fen
print(closest_fen, min_dist)

5rk1/ppp3pp/2q4r/5p1P/7K/2N2NQ1/PP6/3RR3 b - - 15

In [10]:
min_dist = float("inf")
closest_fen = None
for fen in external_puzzles_list:
    dist = Levenshtein.distance("r2kn3/pp3R2/2pbp2q/8/3PN3/4PQ2/PP3P1P/7K w - -", fen)
    if dist < min_dist:
        min_dist = dist
        closest_fen = fen
print(closest_fen, min_dist)

r4n2/pp3Qbk/2p3pp/8/3PN3/4PR2/PqP3PP/6K1 w - - 14