In [1]:
import pandas as pd
from rapidfuzz.distance import Levenshtein
from tqdm import tqdm

In [2]:
df = pd.read_csv("./Generate_positions/generated_puzzles.csv")
df_lichess = pd.read_csv("./Generate_positions/generated_puzzles_lichess_dataset_theme_distribution.csv")
df_lichess_large = pd.read_csv("./Generate_positions/generated_puzzles_lichess_dataset_theme_distribution_large.csv")
df_lichess_correct_ratings = pd.read_csv("./Generate_positions/generated_puzzles_lichess_dataset_theme_distribution_correct_ratings.csv")

In [3]:
print(df["is_legal"].mean(), df[df["is_legal"]]["is_puzzle"].mean(), df[df["is_legal"] & df["is_puzzle"]]["counter_intuitive"].mean())
print(df_lichess["is_legal"].mean(), df_lichess[df_lichess["is_legal"]]["is_puzzle"].mean(), df_lichess[df_lichess["is_legal"] & df_lichess["is_puzzle"]]["counter_intuitive"].mean())
print(df_lichess_large["is_legal"].mean(), df_lichess_large[df_lichess_large["is_legal"]]["is_puzzle"].mean(), df_lichess_large[df_lichess_large["is_legal"] & df_lichess_large["is_puzzle"]]["counter_intuitive"].mean())
print(df_lichess_correct_ratings["is_legal"].mean(), df_lichess_correct_ratings[df_lichess_correct_ratings["is_legal"]]["is_puzzle"].mean(), df_lichess_correct_ratings[df_lichess_correct_ratings["is_legal"] & df_lichess_correct_ratings["is_puzzle"]]["counter_intuitive"].mean())

0.965 0.061139896373056994 0.01694915254237288
0.955 0.2094240837696335 0.01
0.9656 0.21644573322286662 0.0028708133971291866
0.973457532051282 0.1761498096511987 0.027453271028037383

In [6]:
(df_lichess_correct_ratings["is_legal"] & df_lichess_correct_ratings["is_puzzle"] & df_lichess_correct_ratings["counter_intuitive"]).mean()

np.float64(0.004707532051282051)

In [14]:
df_lichess_correct_ratings[df_lichess_correct_ratings["fen"].isna()]

,target_themes,target_rating,fen,is_legal,is_puzzle,counter_intuitive,actual_themes,predicted_rating,themes_match
4798,"['crushing', 'defensiveMove', 'enPassant', 'en...",1942.0,NaN,False,False,NaN,NaN,NaN,NaN
6147,"['crushing', 'defensiveMove', 'endgame', 'skew...",1920.0,NaN,False,False,NaN,NaN,NaN,NaN

In [7]:
dataset = pd.read_csv("./dataset/dataset.csv", chunksize=100_000)
external_puzzles = set()
for chunk in dataset:
    clean_puzzles = chunk["Puzzle_FEN"].str.split(" ").str[:4].str.join(" ")
    external_puzzles.update(clean_puzzles)
print(f"Total unique FENs in external dataset: {len(external_puzzles)}")
processed_lichess_fens = df_lichess_correct_ratings["fen"].fillna("").str.split(" ").str[:4].str.join(" ")
df_lichess_correct_ratings["is_overlap"] = processed_lichess_fens.isin(external_puzzles)
print(df_lichess_correct_ratings["is_overlap"].value_counts())

Total unique FENs in external dataset: 5565407
is_overlap
False    9972
True       12
Name: count, dtype: int64

In [ ]:
external_list = list(external_puzzles)
unique_lichess_fens = processed_lichess_fens.unique()[:100]

min_distances = {}

print(f"Computing distances for {len(unique_lichess_fens)} unique Lichess positions...")

for i, l_fen in tqdm(enumerate(unique_lichess_fens)):
    if not l_fen:
        continue
    
    minimum = min(Levenshtein.distance(l_fen, e_fen) for e_fen in external_list)
    # print(i, minimum)
    min_distances[l_fen] = minimum

df_lichess_correct_ratings["mean_edit_distance"] = processed_lichess_fens.map(min_distances)

avg_dist = df_lichess_correct_ratings["mean_edit_distance"].mean()
print(f"Average min Edit Distance: {avg_dist}")

Computing distances for 100 unique Lichess positions...

100it [06:30,  3.90s/it]

Average min Edit Distance: 13.19

In [9]:
import random


external_list = list(external_puzzles)
sample_size = 100
random_sample_fens = random.sample(external_list, sample_size)

min_distances = {}

print(f"Computing minimum nonzero distances for {sample_size} random positions from external_list...")

for s_fen in tqdm(random_sample_fens):
    if not s_fen:
        continue
    
    distances = (Levenshtein.distance(s_fen, e_fen) for e_fen in external_list)
    nonzero_distances = (d for d in distances if d > 0)
    
    minimum = min(nonzero_distances)
    min_distances[s_fen] = minimum

avg_dist = sum(min_distances.values()) / len(min_distances)
print(f"Average min nonzero Edit Distance: {avg_dist}")

Computing minimum nonzero distances for 100 random positions from external_list...

100%|██████████| 100/100 [06:33<00:00,  3.94s/it]

Average min nonzero Edit Distance: 13.12

In [25]:
df[df["is_legal"] & df["is_puzzle"] & df["counter_intuitive"]]

,target_themes,target_rating,fen,is_legal,is_puzzle,counter_intuitive,actual_themes,predicted_rating,themes_match
47,"['veryLong', 'endgame', 'queenEndgame', 'crush...",2884.556641,6k1/pp1Q1pp1/2p1p2p/2P1P1PP/1P3P2/3K4/8/7q w -...,True,True,True,"['endgame', 'mateIn3', 'mate', 'queenEndgame',...",0.398133,False

In [18]:
df_lichess[df_lichess["is_legal"] & df_lichess["is_puzzle"] & df_lichess["counter_intuitive"]]

,target_themes,target_rating,fen,is_legal,is_puzzle,counter_intuitive,actual_themes,predicted_rating,themes_match
238,"['bishopEndgame', 'crushing', 'defensiveMove',...",125.0,8/7K/6p1/8/6k1/3p4/3B4/8 b - - 0 53,True,True,True,"['endgame', 'advantage', 'advancedPawn', 'quie...",1788.979980,False
350,"['mate', 'mateIn2', 'middlegame', 'short']",24.0,3r2k1/pp1q3p/6p1/2Q1RnN1/5R2/P5Pb/1P2P2P/6K1 b...,True,True,True,"['middlegame', 'mateIn2', 'mate', 'short']",1050.020508,True

In [ ]:
with pd.option_context("display.max_colwidth", 500):
    display(df_lichess_large[df_lichess_large["is_legal"] & df_lichess_large["is_puzzle"] & df_lichess_large["counter_intuitive"]][["fen", "target_themes", "actual_themes", "predicted_rating"]])

,fen,target_themes,actual_themes,predicted_rating
1022,N4k2/3n2r1/pp1P1p1n/5Pqp/2P2pp1/1P6/P3RPPP/4R1K1 w - - 0 30,"['fork', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'short']",626.755493
3869,4k3/Rp1n1qpr/2p1r3/B7/2p5/2P4P/2P1QbP1/4R2K w - - 0 29,"['advantage', 'fork', 'long', 'middlegame']","['middlegame', 'advantage', 'exposedKing', 'long']",1872.460571
5814,7k/1b2r1p1/5r2/p1pp4/3q1b2/P1N5/1P2QPPP/1B2R1K1 w - - 0 28,"['long', 'mate', 'mateIn3', 'middlegame', 'sacrifice']","['middlegame', 'advantage', 'discoveredAttack', 'kingsideAttack', 'short']",1411.959717
7458,6k1/p2nr1Pr/1p5p/1b1p4/3P3q/4PR2/PP3RPP/5QK1 w - - 1 29,"['advancedPawn', 'mate', 'mateIn2', 'middlegame', 'promotion', 'short']","['middlegame', 'mateIn3', 'mate', 'exposedKing', 'kingsideAttack', 'long']",1248.470703
7710,r3r1k1/pp1b1ppp/8/q2pR3/5N2/1P6/1P2QPPP/4R1K1 w - - 0 20,"['advantage', 'fork', 'middlegame', 'veryLong']","['middlegame', 'mateIn3', 'mate', 'backRankMate', 'long']",775.752197
9797,6kq/p1pr1p1p/1bp3pP/8/4N3/6Pb/PPP2P2/4R1KR w - - 0 24,"['discoveredAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'kingsideAttack', 'short']",1005.286377

In [8]:
with pd.option_context("display.max_colwidth", 500):
    display(df_lichess_correct_ratings[df_lichess_correct_ratings["is_legal"] & df_lichess_correct_ratings["is_puzzle"] & df_lichess_correct_ratings["counter_intuitive"]][["fen", "target_themes", "actual_themes", "predicted_rating"]])

,fen,target_themes,actual_themes,predicted_rating
219,r1bq1r1k/p5bp/1pn1Q1p1/n1p3N1/P1B2P2/2PP4/6PP/R1B2RK1 w - - 5 18,"['kingsideAttack', 'master', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short', 'smotheredMate']","['middlegame', 'mateIn2', 'mate', 'smotheredMate', 'sacrifice', 'kingsideAttack', 'short']",1534.806641
229,8/5p1p/2k2Bp1/8/3p1PP1/6KP/1bP5/8 b - - 1 36,"['bishopEndgame', 'crushing', 'endgame', 'short', 'skewer']","['endgame', 'advantage', 'discoveredAttack', 'bishopEndgame', 'short']",1107.149170
384,5rk1/5qpp/4p3/3pQ3/3P4/6R1/PPr2PPP/5RK1 b - - 1 25,"['endgame', 'master', 'mate', 'mateIn4', 'sacrifice', 'veryLong']","['endgame', 'mateIn4', 'mate', 'sacrifice', 'veryLong']",1475.327026
401,r1bq1rk1/1pp2pp1/2nb1n2/p2Np1Np/3P3P/4P3/PPQ2PP1/R1B1KB1R w KQ - 0 11,"['kingsideAttack', 'mate', 'mateIn2', 'opening', 'short']","['middlegame', 'mateIn2', 'mate', 'kingsideAttack', 'short']",1221.063110
419,r4r1k/pp2Nppp/4n3/3p3R/8/2P1R3/PP6/2K5 w - - 1 25,"['anastasiaMate', 'attraction', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn2', 'mate', 'anastasiaMate', 'attraction', 'sacrifice', 'short']",1389.271729
657,r1bqrbk1/1p1p1R1p/p1p3p1/4PN1n/2Bn1P2/2N5/PPP2P1P/R3K2R w KQ - 0 18,"['doubleCheck', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'doubleCheck', 'kingsideAttack', 'short']",1997.696777
740,r2q1r1k/1b3p2/1p2pNnb/3pP3/8/pPp1P1P1/P1P1BPK1/3R3R w - - 0 24,"['hookMate', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'hookMate', 'hangingPiece', 'kingsideAttack', 'short']",1096.088745
749,2R2r1k/pp5p/4Q1n1/4p3/4P2P/6PB/P4P1K/3q1r2 w - - 11 31,"['attraction', 'long', 'mate', 'mateIn3', 'middlegame', 'sacrifice']","['middlegame', 'mateIn2', 'mate', 'pin', 'short']",1541.887451
1035,6k1/5p2/p4B1p/1pbpQ3/8/2PB3P/5qbK/8 w - - 0 30,"['advantage', 'deflection', 'endgame', 'master', 'veryLong']","['endgame', 'mateIn4', 'mate', 'attraction', 'deflection', 'sacrifice', 'fork', 'veryLong']",2009.621704
1154,2r2r2/1p3pkp/p4np1/2P1Q3/5N2/3BP2P/3q1PP1/5RK1 w - - 0 26,"['advantage', 'middlegame', 'short']","['middlegame', 'advantage', 'deflection', 'sacrifice', 'long']",1913.974365
1158,1Q1R4/5pkp/1p1p4/2rPp3/1P6/8/PPq1r2P/KR6 b - - 0 33,"['attraction', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'short']",1402.728027
1176,2k5/2p2ppp/pq6/1p4Q1/8/Pr3P1P/5P2/4R1K1 w - - 0 25,"['advantage', 'defensiveMove', 'endgame', 'veryLong']","['endgame', 'advantage', 'deflection', 'fork', 'veryLong']",1835.946655
1497,8/R5pp/1p4k1/2p3rn/P3P3/4bP2/1PP3PP/3R3K b - - 0 24,"['clearance', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'short']",1074.838135
1783,2b3k1/2p3pp/3p2r1/3Pp2q/2P1Pp2/5P2/5QPP/4N1RK b - - 3 33,"['attraction', 'endgame', 'kingsideAttack', 'master', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn3', 'mate', 'attraction', 'sacrifice', 'kingsideAttack', 'long']",1266.761475
2284,2k1r2r/ppq2p2/3bb1p1/2pN4/6P1/1P6/P1PPQPB1/R3R1K1 b - - 0 19,"['advantage', 'kingsideAttack', 'long', 'middlegame', 'sacrifice']","['middlegame', 'advantage', 'veryLong']",1984.945557
2534,5rk1/ppb1q3/2p3pQ/5p1R/4p3/2P5/PP3PPP/6K1 w - - 0 33,"['endgame', 'mate', 'mateIn2', 'short']","['endgame', 'advantage', 'exposedKing', 'skewer', 'long']",1650.163452
2888,6r1/5p1p/2Qpk3/4p3/5qr1/8/PPP1RP1P/R6K b - - 5 26,"['endgame', 'master', 'mate', 'mateIn1', 'oneMove']","['endgame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'short']",1726.293701
2952,4r2k/pp1R4/5R1p/5pnQ/1q6/7P/P5P1/7K b - - 7 35,"['advantage', 'endgame', 'long']","['endgame', 'mateIn3', 'mate', 'long']",1241.219482
3142,r1Bq1rk1/2p3pp/p7/1pb1pp2/3nP3/3P3P/PPP3PN/R1BQ1RK1 b - - 0 14,"['doubleCheck', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'doubleCheck', 'kingsideAttack', 'short']",1683.158203
3590,1nr3k1/6p1/p3p2r/3pNp1n/1P1P3q/P1P5/3BBPP1/R2Q1RK1 b - - 4 29,"['attraction', 'doubleCheck', 'kingsideAttack', 'long', 'mate', 'mateIn3', 'middlegame', 'sacrifice']","['middlegame', 'mateIn3', 'mate', 'attraction', 'doubleCheck', 'sacrifice', 'kingsideAttack', 'long']",1791.171997
3657,2r2rk1/pbq1bpp1/1p1ppn1p/2p3NN/1PP5/P2QP3/1B1P1PPP/R3K2R w KQ - 0 15,"['kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'kingsideAttack', 'short']",1300.223877
4182,4r1k1/2p2p2/p2q1Pp1/1p4QR/6P1/1PP4K/8/1b6 w - - 1 28,"['attraction', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'attraction', 'sacrifice', 'long']",1423.131348
4228,3r1rk1/p3p2p/6pQ/2q5/8/6R1/PP3PPP/5RK1 b - - 2 26,"['endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'sacrifice', 'long']",1328.694580
4691,8/1R6/6pk/p2p4/1p1P1PP1/6K1/8/1r6 w - - 2 52,"['endgame', 'mate', 'mateIn2', 'rookEndgame', 'short']","['endgame', 'mateIn2', 'mate', 'rookEndgame', 'short']",949.715332
4719,1R4nk/5ppp/pQ1p1r2/2p5/2P2P2/8/q5PP/6K1 w - - 0 29,"['attraction', 'backRankMate', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'backRankMate', 'attraction', 'sacrifice', 'short']",1097.133545
5012,r1bq2kr/p4pbp/3p2pB/1ppP4/2n1N3/5Q1P/PPP2PP1/R3R1K1 w - - 2 17,"['advantage', 'kingsideAttack', 'long', 'middlegame', 'sacrifice']","['middlegame', 'advantage', 'short']",2044.560181
5149,2kr4/1p3pRp/p1pq4/8/4Q3/8/PPP2P1P/2K1R3 b - - 0 23,"['backRankMate', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'backRankMate', 'sacrifice', 'long']",1126.882812
5311,b4rk1/2p2ppp/p1p5/1pP1q3/8/PQ6/BP4PP/3R2K1 w - - 0 21,"['endgame', 'fork', 'long', 'mate', 'mateIn3', 'pin', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'sacrifice', 'fork', 'pin', 'long']",1333.272339
5929,7q/8/r4pp1/3p3p/8/p3PkPQ/1r3P2/3R2K1 w - - 4 42,"['discoveredAttack', 'endgame', 'long', 'mate', 'mateIn3']","['endgame', 'crushing', 'discoveredAttack', 'short']",1665.850952
6189,4r1k1/1p4pp/8/p7/P3q2P/1Pb2Q2/6P1/5R1K w - - 0 27,"['backRankMate', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'backRankMate', 'sacrifice', 'long']",1152.665283
6465,r4nk1/6pp/p2p4/1p3Q1B/3qbR2/8/PP4PP/7K w - - 0 29,"['backRankMate', 'deflection', 'long', 'mate', 'mateIn3', 'middlegame']","['middlegame', 'mateIn3', 'mate', 'backRankMate', 'deflection', 'long']",1398.461182
6943,2k1r3/ppp1q2p/6p1/8/5R2/1QP2N2/PP3PPP/5K2 b - - 0 23,"['backRankMate', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'backRankMate', 'sacrifice', 'long']",1044.314209
7449,6k1/ppp2pp1/3b3p/3P4/2P1b2N/1Q4PP/PP2rR2/6K1 b - - 3 28,"['endgame', 'mate', 'mateIn2', 'short']","['endgame', 'crushing', 'short']",1670.359863
7454,8/6Q1/3Pb2p/3qPk2/7P/4B1K1/8/1q6 w - - 0 58,"['endgame', 'master']","['endgame', 'mateIn2', 'mate', 'short']",1644.651978
7482,5r1k/1p4p1/p2p1qQp/3B4/4R3/8/P1P3PP/4R1K1 b - - 3 30,"['backRankMate', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'backRankMate', 'sacrifice', 'long']",1156.782959
7626,5rkb/p4p2/1p1rpqNp/2p5/4Q3/2P5/PPB2PP1/4R1K1 w - - 1 26,"['clearance', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short']","['middlegame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'kingsideAttack', 'short']",1210.318848
7660,2r3k1/p4ppp/1pQ1b3/1N2P3/8/7q/PPP4P/2KR4 w - - 4 26,"['backRankMate', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'backRankMate', 'sacrifice', 'short']",1105.174316
7825,7k/2qrb1p1/5pP1/p1p1p3/PpP1Q3/1P2BK1P/3r1P2/8 w - - 0 33,"['long', 'mate', 'mateIn3', 'middlegame']","['endgame', 'mateIn3', 'mate', 'kingsideAttack', 'long']",1058.062256
8171,r1bq3r/pp3pk1/2p3p1/3pP3/3P1Pn1/P1NB2P1/1P1QR1P1/2R3K1 b - - 8 21,"['attraction', 'kingsideAttack', 'mate', 'mateIn4', 'middlegame', 'sacrifice', 'veryLong']","['middlegame', 'mateIn4', 'mate', 'attraction', 'sacrifice', 'kingsideAttack', 'veryLong']",1464.785522
8642,5rk1/1p3ppp/p4r2/3R4/8/Q5P1/PPq2P1P/4R1K1 w - - 1 24,"['attraction', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'short']",1189.107666
8678,6k1/p3R1pp/2Q1pr2/8/3r4/1P6/q4PPP/5RK1 b - - 1 26,"['endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'sacrifice', 'long']",1428.974609
8801,4k1r1/2q1bp2/pp3p2/3p1Q2/3P4/2P2NPp/PP6/4RRK1 b - - 0 24,"['kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'short']","['middlegame', 'mateIn2', 'mate', 'kingsideAttack', 'short']",1075.740234
9107,r2q1rk1/pb3pp1/1p2p2p/2p5/2PPNn1P/3Q4/PPB2PP1/2KRR3 w - - 3 20,"['clearance', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short']","['middlegame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'kingsideAttack', 'short']",1004.034851
9429,r4bk1/pbp3pp/2q5/2p2Q2/7r/2N4P/PPP3P1/R4RK1 w - - 0 23,"['backRankMate', 'deflection', 'long', 'mate', 'mateIn3', 'middlegame', 'sacrifice']","['middlegame', 'mateIn3', 'mate', 'backRankMate', 'deflection', 'long']",1099.663086
9498,2r1r1k1/5ppp/R7/1p3Q2/3P4/8/1P3PPP/2q2RK1 b - - 2 21,"['attraction', 'endgame', 'mate', 'mateIn2', 'sacrifice', 'short']","['endgame', 'mateIn2', 'mate', 'attraction', 'sacrifice', 'short']",1185.277588
9739,r4rk1/1b2bpp1/p3p2p/1p6/2n1Nq2/2PQ1N1P/PPB2PP1/R4RK1 w - - 3 19,"['clearance', 'kingsideAttack', 'mate', 'mateIn2', 'middlegame', 'sacrifice', 'short']","['middlegame', 'mateIn2', 'mate', 'sacrifice', 'clearance', 'kingsideAttack', 'short']",1061.611694
9901,5rk1/5ppp/8/4P3/2Q5/1p4PK/rq2P2P/2R2R2 w - - 0 30,"['clearance', 'endgame', 'long', 'mate', 'mateIn3', 'sacrifice']","['endgame', 'mateIn3', 'mate', 'sacrifice', 'clearance', 'long']",1402.480225